language: java
jdk:
- openjdk11

sudo: required
services:
  - docker

install:
  - mvn install

script:
  - docker build -t inseefr/queen-bo .

before_script:
  - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.17.0/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/

deploy:
  - skip_cleanup: true
    provider: script
    script:
      echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
      && docker push inseefr/queen-bo
    on:
      branch: master

  - skip_cleanup: true
    provider: script
    script:
      kubectl --token $K8S_TOKEN --server $K8S_SERVER --insecure-skip-tls-verify rollout restart deployment/queen-bo -n queen
    on:
      branch: master

